services:
  minecraft:
    # Konfiguracja Dockera
    image: "itzg/minecraft-server:java17-graalvm"
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft/gl5:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mc-health"]
      start_period: 210s #3,5m
      interval: 3s
      retries: 40
    # Konfiguracja MC
    environment:
      # Wersja
      TYPE: "FABRIC"
      FABRIC_LAUNCHER_VERSION: "1.0.1"
      FABRIC_LOADER_VERSION: "0.15.11"
      VERSION: "1.20.1"
      # Minecraft stuff
      GUI: "FALSE"
      EULA: "TRUE"              #  Dlaczego niektóre wartości boolean są pisane wielką literą...
      # Java stuff
      MEMORY: "20G"
      USE_AIKAR_FLAGS: "true"   #  ...a inne małą? No fucking idea! Ale tak było w docsach, więc się trzymam.
      # Misc
      UID: "42069"
      GID: "%DOCKER_GROUP_ID%"
      TZ: "Europe/Warsaw"
      LOG_TIMESTAMP: "true"
#  
  #backuper:
    #image: itzg/mc-backup
    #user: "42069"
    #depends_on:
      #minecraft:
        #condition: service_healthy
    #environment:
      #BACKUP_INTERVAL: "10h"
      #RCON_HOST: "minecraft"
      #INITIAL_DELAY: 0
      #EXCLUDES: "*.jar,cache,logs,*.tmp,.cache,.e4mc_cache,.fabric,.mixin.out,crash-reports,immersive_paintings_cache,libraries,modernfix,versions,usercache.json,usernamecache.json"
      #TZ: "Europe/Warsaw"
      #BACKUP_NAME: "full"
      #PRUNE_BACKUPS_DAYS: 3
    #volumes:
      #- ./minecraft/gl5:/data:ro
      #- ./backups/gl5:/backups
